apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-backup-debug
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - pods/exec
  verbs:
    - create
    - get
    - list
    - watch
    - delete
