apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: YWRtaW46JDJ5JDA1JGkzSmI2ZFNRNEhMRExlUDRSbFNlWWU5MWtKanF4cm85ajZyZmRPOVJ5WDdrUDJBbEFINE1tCg==
