apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bridge-vlan30
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  desiredState:
    interfaces:
      - name: br-vlan30
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens224.30    #need to check in vlan spec name