apiVersion: batch/v1
kind: CronJob
metadata:
  name: openshift-backup
  namespace: ocp-etcd-backup
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: openshift-backup
          restartPolicy: Never
          containers:
          - name: backup
            image: registry.redhat.io/openshift4/ose-cli:latest
            command:
            - /bin/bash
            - -c
            - |
              echo "Starting ETCD backup..."
              oc get nodes -l node-role.kubernetes.io/master --no-headers -o name | head -n 1 | \
              xargs -I {} oc debug {} --to-namespace=ocp-etcd-backup -- bash -c '
                mkdir -p /host/home/core/backup &&
                chroot /host /usr/local/bin/cluster-backup.sh /home/core/backup &&
                chroot /host find /home/core/backup -type f -mtime +7 -delete
              '
              echo "ETCD backup completed."
