apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: openshift-etcd-backup
spec:
  schedule: "0 1 * * *"   # daily 1 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: etcd-backup-sa
          restartPolicy: Never
          containers:
          - name: etcd-backup
            image: registry.redhat.io/openshift4/ose-etcd:latest
            command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Starting ETCD backup..."
              /usr/local/bin/cluster-backup.sh /backup
              echo "Backup completed"
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: etcd-backup-pvc
