apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: openshift-etcd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: etcd-backup-sa
          restartPolicy: Never
          hostPID: true
          containers:
          - name: etcd-backup
            image: registry.redhat.io/openshift4/ose-etcd:latest
            command:
            - /bin/bash
            - -c
            - |
              chroot /host /usr/local/bin/cluster-backup.sh /home/core/etcd-backup
            volumeMounts:
            - name: host
              mountPath: /host
          volumes:
          - name: host
            hostPath:
              path: /
              type: Directory
