apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: openshift-etcd-backup
spec:
  schedule: "0 1 * * *"   # Daily 1 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: etcd-backup-sa
          restartPolicy: Never
          containers:
          - name: etcd-backup
            image: registry.redhat.io/openshift4/ose-cli:latest
            command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Starting ETCD backup..."
              oc get nodes -l node-role.kubernetes.io/master --no-headers -o name | head -n 1 | xargs -I {} \
                oc debug {} --to-namespace=openshift-etcd-backup -- bash -c '
                  mkdir -p /host/home/core/etcd-backup &&
                  chroot /host /usr/local/bin/cluster-backup.sh /home/core/etcd-backup
                '
              echo "ETCD backup completed"
