apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcd-backup-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: etcd-backup-rolebinding
subjects:
- kind: ServiceAccount
  name: etcd-backup-sa
  namespace: openshift-etcd-backup
roleRef:
  kind: ClusterRole
  name: etcd-backup-role
  apiGroup: rbac.authorization.k8s.io
